name: indifiles_annotation_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python==3.8
  - pandas
  - matchms
  - tqdm
  - plotly
  - pip
  - pyyaml
  - pip :
    - opentree
