name: indifiles_annotation_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python==3.9
  - pandas==2.0.2
  - numpy==1.24.3
  - matchms==0.20.0
  - tqdm==4.65.0
  - plotly==5.14.1
  - pip==23.1.2
  - pyyaml==6.0
  - pip :
    - opentree==1.0.1
    - GitPython==3.1.31